name: 'collect issues'
author: 'Johannes Lumpe'
description: 'Collects issue numbers from issues which match patterns and writes the result to an output file'
inputs:
  title-filter:
    description: 'Filter to be used when matching issue titles, can be a string or a serialized array of patterns'
    required: true
  label-filter:
    description: 'Filter to be used when matching issue titles, can be a string or a serialized array of patterns'
    required: true
  repo-token:
      description: 'Github repo access token'
      required: true
  env-output-variable:
      description: 'Environment variable name wich will be used to store serialized action results for further processing'
      required: true
      default: 'COLLECTED_ISSUE_NUMBERS'
outputs:
  issue_message_json:
    description: ''
runs:
  using: 'node12'
  main: 'lib/index.js'